/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#343535",
        "on-surface": "#e3e2e2",
        "surface-container": "#1e2020",
        "background": "#121414",
        "outline": "#859399",
        "primary-container": "#00d2ff",
        "inverse-primary": "#00677f",
        "outline-variant": "#3c494e",
        "surface-tint": "#47d6ff",
        "primary-fixed": "#b6ebff",
        "on-surface-variant": "#bbc9cf",
        "on-background": "#e3e2e2",
        "surface-variant": "#343535",
        "on-tertiary-fixed-variant": "#474646",
        "surface-container-lowest": "#0d0e0f",
        "primary-fixed-dim": "#47d6ff",
        "surface-container-high": "#292a2a",
        "on-primary-fixed-variant": "#004e60",
        "tertiary": "#dfdcdb",
        "on-tertiary": "#313030",
        "tertiary-container": "#c3c0c0",
        "primary": "#a5e7ff",
        "inverse-on-surface": "#2f3131",
        "on-primary-container": "#00566a",
        "secondary-fixed-dim": "#edb1ff",
        "surface": "#121414",
        "on-tertiary-fixed": "#1c1b1b",
        "on-primary-fixed": "#001f28",
        "on-secondary-fixed-variant": "#6e208c",
        "on-tertiary-container": "#4f4e4e",
        "inverse-surface": "#e3e2e2",
        "secondary": "#edb1ff",
        "surface-bright": "#383939",
        "tertiary-fixed-dim": "#c9c6c5",
        "surface-dim": "#121414",
        "on-primary": "#003543",
        "secondary-container": "#6e208c",
        "on-error": "#690005",
        "surface-container-low": "#1a1c1c",
        "on-secondary": "#520070",
        "on-error-container": "#ffdad6",
        "secondary-fixed": "#f9d8ff",
        "on-secondary-fixed": "#320046",
        "on-secondary-container": "#e498ff",
        "tertiary-fixed": "#e5e2e1",
        "error": "#ffb4ab",
        "error-container": "#93000a"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        base: "8px",
        gutter: "24px",
        "container-max": "1280px",
        "margin-mobile": "16px",
        "margin-desktop": "40px"
      },
      fontFamily: {
        "headline-md": ["Outfit", "sans-serif"],
        "body-md": ["Outfit", "sans-serif"],
        "code-sm": ["JetBrains Mono", "monospace"],
        "body-lg": ["Outfit", "sans-serif"],
        "display-lg-mobile": ["Outfit", "sans-serif"],
        "display-lg": ["Outfit", "sans-serif"],
        "headline-sm": ["Outfit", "sans-serif"],
        "label-caps": ["JetBrains Mono", "monospace"]
      },
      fontSize: {
        "headline-md": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "code-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "display-lg-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-sm": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
}
